language: python

python: 3.7

dist: xenial

sudo: true

addons:
  apt:
    packages:
    - libcairo2
    - libcairo2-dev

branches:
  only:
  - master

script:
  - pip install .
  - python setup.py test
  - python setup.py sdist bdist
