language: python

python: 
  - "3.6"

script:
  - git clone https://github.com/shawnmjones/archiveit_utilities.git /tmp/archiveit_utilities
  - pip install /tmp/archiveit_utilities
  - rm -rf /tmp/archiveit_utilities
  - pip install .
  - chmod 0755 tests/deploycache.sh
  - chmod 0755 tests/savecache.sh
  - python setup.py test
  - python setup.py sdist bdist